//https://forge.integrations-lab-forge.deltatre.digital/deltatre.forge.vsm/api/menus/475183FD-CEBE-4C56-90E9-28895782CC29

const footerMenu = {
  data: {
    variables: [],
    items: [
      {
        id: '13012066-b02f-4213-b00e-691804f438fc',
        text: 'Contact',
        tag: 'contact',
        link: 'link',
        target: 'target',
        tooltip: 'tooltip',
        visible: true,
        icon: {},
        properties: {
          data: 'custom-prop',
        },
        items: [],
      },
      {
        id: '6cf370a6-dec1-4632-950c-123243d10923',
        text: 'supercars-tenders',
        tag: 'supercars-tenders',
        link: '',
        target: '',
        tooltip: '',
        visible: true,
        icon: {},
        properties: {},
        items: [
          {
            id: 'ss04e0423e-3da2-4c9c-88b9-a4d29089b329',
            text: 'submenu',
            tag: 'submenu supercars-job',
            link: '',
            target: '',
            tooltip: '',
            visible: true,
            icon: {},
            properties: {},
            items: [],
          },
        ],
      },
      {
        id: '04e0423e-3da2-4c9c-88b9-a4d29089b329',
        text: 'supercars-job',
        tag: 'supercars-job',
        link: '',
        target: '',
        tooltip: '',
        visible: true,
        icon: {},
        properties: {},
        items: [],
      },
      {
        id: '591afec6-134c-47e3-b34b-425784301fc8',
        text: 'media',
        tag: 'media',
        link: '',
        target: '',
        tooltip: '',
        visible: true,
        icon: {},
        properties: {},
        items: [],
      },
      {
        id: '551cf9d2-44d3-4ca3-9797-59924cfd2bfd',
        text: 'news-rss',
        tag: 'news-rss',
        link: '',
        target: '',
        tooltip: '',
        visible: true,
        icon: {},
        properties: {},
        items: [],
      },
      {
        id: '916aede7-8f53-4a04-8e98-3951f2fd11e8',
        text: 'sitemap',
        tag: 'sitemap',
        link: '',
        target: '',
        tooltip: '',
        visible: true,
        icon: {},
        properties: {},
        items: [],
      },
      {
        id: '700d8f31-7dc9-4d65-b468-a2b00026dac8',
        text: 'privacy-policy',
        tag: 'privacy-policy',
        link: '',
        target: '',
        tooltip: '',
        visible: true,
        icon: {},
        properties: {},
        items: [],
      },
      {
        id: '1dc39a9f-00e0-45a4-9ba9-67653375055d',
        text: 'terms-&-conditions',
        tag: 'terms-&-conditions',
        link: '',
        target: '',
        tooltip: '',
        visible: true,
        icon: {},
        properties: {},
        items: [],
      },
    ],
    name: '_footer-menu',
    path: '~/_footer-menu',
  },
  meta: {
    version: '1.0',
  },
};

export { footerMenu };
