nodeLinker: node-modules

npmScopes:
  deltatre-vxp:
    npmAuthToken: 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
    npmRegistryServer: "https://npm.pkg.github.com/"
  d3-forge:
    npmRegistryServer: https://alm.deltatre.it/tfs/D3Alm/_packaging/platforms.team.webplu/npm/registry/
    npmAuthIdent: RDNBbG06Z2VjM2liYWh6dWdkbTdwM3prejZ3amNlNGNhb2x6ZmlmZGRkY3J4amR2aTRpMm9zM2JkcQ==
    npmAlwaysAuth: true