resources:
  repositories:
    - repository: templates
      name: SXP-DevOps/d3ops-pipelines-templates
      type: git
      ref: "refs/tags/build/common-solution/steps/1.1.3"

schedules:
  - cron: "0 5 * * *"
    displayName: 05:00 AM build
    branches:
      include:
        - main
    always: true

trigger: none
pool:
  name: WebPlu
  demands:
    - Docker

variables:
  system.debug: "true"

steps:
  # Create GitFinalVersion variable
  - template: build/common-solution/steps/set-version-universal.yml@templates

  - task: NodeTool@0
    displayName: 'Use Node 10.x'
    inputs:
      versionSpec: 10.x

  - task: jyc.vsts-extensions-renovate-me.default-build-task.RenovateMe@1
    displayName: Renovate
    inputs:
      renovateOptionsVersion: 19.55.0
      renovateOptionsArgs: ' --log-level=debug'