import { ForgeEntityCode } from '@/models/types/forge';

const sampleStories = [
  {
    type: ForgeEntityCode.story,
    _translationId: '21d9a0d7-8353-4a5d-8b1a-ef919b64e7f0',
    _entityId: '1d2880b0-bbc5-4b76-b7c4-053c5c8a8707',
    selfUrl: 'https://forge-dapi.ifsc-dev.deltatre.digital/v2/content/en-gb/stories/test-story-without-thumbnail',
    slug: 'test-story-without-thumbnail',
    title: 'test story without thumbnail',
    tags: [],
    fields: {},
    createdBy: 'Francesco Talomo',
    lastUpdatedBy: 'Francesco Talomo',
    lastUpdatedDate: '2023-10-25T07:19:23.876Z',
    contentDate: '2023-10-25T07:19:23.876Z',
    featured: 0,
    summary: 'test story without thumbnail',
  },
  {
    type: ForgeEntityCode.story,
    _translationId: '69cde944-9844-437c-b1c0-6b3f00f50285',
    _entityId: 'bd82cdf4-580f-452e-8b63-7cb21f18ff93',
    selfUrl:
      'https://forge-dapi.ifsc-dev.deltatre.digital/v2/content/en-gb/stories/ifsc-celebrates-international-women-s-day',
    slug: 'ifsc-celebrates-international-women-s-day',
    title: "IFSC CELEBRATES INTERNATIONAL WOMEN'S DAY",
    tags: [
      {
        _translationId: 'de58d9e6-fbba-4294-95bd-36dd7674575d',
        _entityId: '658ce627-3763-471f-b451-e04cda2f745b',
        selfUrl: 'https://forge-dapi.ifsc-dev.deltatre.digital/v2/content/en-gb/tags/lukas-franckaert-336',
        title: 'Lukas FRANCKAERT',
        slug: 'lukas-franckaert-336',
        neutralSlug: 'lukas-franckaert-336',
        externalSourceName: 'athletes',
        externalSourceReference: {
          SourceId: '336',
          SourceName: 'athletes',
        },
        extraData: {
          birthday: '2000-02-16',
          country: 'BEL',
          federation: {
            id: 9,
            name: 'Climbing and Mountaineering Belgium',
            abbreviation: 'CMBEL',
            url: 'www.cmbel.be',
          },
          firstName: 'Lukas',
          gender: 'male',
          lastName: 'FRANCKAERT',
        },
        fields: {},
      },
      {
        _translationId: 'fc8608c0-3014-4fff-98bf-9478efd93307',
        _entityId: '54c61796-6979-4170-b1cd-129e2dc2ff80',
        selfUrl: 'https://forge-dapi.ifsc-dev.deltatre.digital/v2/content/en-gb/tags/raffaele-leo-1806',
        title: 'Raffaele LEO',
        slug: 'raffaele-leo-1806',
        neutralSlug: 'raffaele-leo-1806',
        externalSourceName: 'athletes',
        externalSourceReference: {
          SourceId: '1806',
          SourceName: 'athletes',
        },
        extraData: {
          birthday: '1997-12-03',
          country: 'USA',
          federation: {
            id: 20,
            name: 'USA Climbing',
            abbreviation: 'USAC',
          },
          firstName: 'Raffaele',
          gender: 'male',
          lastName: 'LEO',
        },
        fields: {},
      },
      {
        _translationId: 'c2e739e1-7836-4deb-b438-d0c091b28f6a',
        _entityId: 'ac4ab29e-fb85-4977-bf79-fd2dc5fbbf23',
        selfUrl: 'https://forge-dapi.ifsc-dev.deltatre.digital/v2/content/en-gb/tags/leo-avezou-505',
        title: 'Leo AVEZOU',
        slug: 'leo-avezou-505',
        neutralSlug: 'leo-avezou-505',
        externalSourceName: 'athletes',
        externalSourceReference: {
          SourceId: '505',
          SourceName: 'athletes',
        },
        extraData: {
          birthday: '1999-08-21',
          country: 'FRA',
          federation: {
            id: 10,
            name: "Federation Française de la Montagne et de l'Escalade",
            abbreviation: 'FFME',
            url: 'www.ffme.fr',
          },
          firstName: 'Leo',
          gender: 'male',
          lastName: 'AVEZOU',
        },
        fields: {},
      },
      {
        _translationId: 'fc721163-6fb3-47b6-b7b6-12f27f68b4c7',
        _entityId: '7651d034-042f-42b1-b1b1-d8b003ddfec2',
        selfUrl: 'https://forge-dapi.ifsc-dev.deltatre.digital/v2/content/en-gb/tags/leo-favot-574',
        title: 'Leo FAVOT',
        slug: 'leo-favot-574',
        neutralSlug: 'leo-favot-574',
        externalSourceName: 'athletes',
        externalSourceReference: {
          SourceId: '574',
          SourceName: 'athletes',
        },
        extraData: {
          birthday: '2000-03-09',
          country: 'FRA',
          federation: {
            id: 10,
            name: "Federation Française de la Montagne et de l'Escalade",
            abbreviation: 'FFME',
            url: 'www.ffme.fr',
          },
          firstName: 'Leo',
          gender: 'male',
          lastName: 'FAVOT',
        },
        fields: {},
      },
      {
        _translationId: '76c9c9f0-991e-446f-b37b-8c64f8124d2d',
        _entityId: '5126ca2c-3cf8-4569-a217-d3cb759a40b9',
        selfUrl: 'https://forge-dapi.ifsc-dev.deltatre.digital/v2/content/en-gb/tags/franklin-flament-362',
        title: 'Franklin FLAMENT',
        slug: 'franklin-flament-362',
        neutralSlug: 'franklin-flament-362',
        externalSourceName: 'athletes',
        externalSourceReference: {
          SourceId: '362',
          SourceName: 'athletes',
        },
        extraData: {
          birthday: '2003-05-29',
          country: 'BEL',
          federation: {
            id: 9,
            name: 'Climbing and Mountaineering Belgium',
            abbreviation: 'CMBEL',
            url: 'www.cmbel.be',
          },
          firstName: 'Franklin',
          gender: 'male',
          lastName: 'FLAMENT',
        },
        fields: {},
      },
      {
        _translationId: '7a9dcdbc-67b2-4297-99d9-ffe344cb6525',
        _entityId: '218b7dce-1831-4a85-baf3-cac1a4425cc8',
        selfUrl: 'https://forge-dapi.ifsc-dev.deltatre.digital/v2/content/en-gb/tags/gregorz-grochal-7028',
        title: 'Gregorz GROCHAL',
        slug: 'gregorz-grochal-7028',
        neutralSlug: 'gregorz-grochal-7028',
        externalSourceName: 'athletes',
        externalSourceReference: {
          SourceId: '7028',
          SourceName: 'athletes',
        },
        extraData: {
          country: 'POL',
          federation: {
            id: 36,
            name: 'Polski Zwiazek Alpinizmu',
            abbreviation: 'PZA',
            url: 'http://pza.org.pl',
          },
          firstName: 'Gregorz',
          gender: 'male',
          lastName: 'GROCHAL',
        },
        fields: {},
      },
      {
        _translationId: '16e85c76-1771-4190-8396-b87a06fa6ade',
        _entityId: '60705b6c-7bf4-4145-b662-c9f846aecc5c',
        selfUrl: 'https://forge-dapi.ifsc-dev.deltatre.digital/v2/content/en-gb/tags/lucia-miranda-cid-837',
        title: 'Lucia MIRANDA CID',
        slug: 'lucia-miranda-cid-837',
        neutralSlug: 'lucia-miranda-cid-837',
        externalSourceName: 'athletes',
        externalSourceReference: {
          SourceId: '837',
          SourceName: 'athletes',
        },
        extraData: {
          birthday: '2004-04-28',
          country: 'ESP',
          federation: {
            id: 12,
            name: 'Federación Española de Deportes de Montaña y Escalada',
            abbreviation: 'FEDME',
          },
          firstName: 'Lucia',
          gender: 'female',
          lastName: 'MIRANDA CID',
        },
        fields: {},
      },
      {
        _translationId: 'b92161bb-1de4-4ca7-93f7-d0d717e7b2ff',
        _entityId: 'ae253362-d715-4e78-8119-8d9f6583f0d0',
        selfUrl: 'https://forge-dapi.ifsc-dev.deltatre.digital/v2/content/en-gb/tags/korbinian-franck-14',
        title: 'Korbinian FRANCK',
        slug: 'korbinian-franck-14',
        neutralSlug: 'korbinian-franck-14',
        externalSourceName: 'athletes',
        externalSourceReference: {
          SourceId: '14',
          SourceName: 'athletes',
        },
        extraData: {
          birthday: '1989-09-02',
          country: 'GER',
          federation: {
            id: 6,
            name: 'Deutscher Alpenverein',
            abbreviation: 'DAV',
          },
          firstName: 'Korbinian',
          gender: 'male',
          lastName: 'FRANCK',
          paraclimbingSportClass: 'Limited Range, Power & Stability 1: RP1',
        },
        fields: {},
      },
      {
        _translationId: '8e2e0196-5625-41f0-b0c3-1c45c0c9d4b5',
        _entityId: '9b07de58-af67-4f3e-b3fb-5e2e939ff0de',
        selfUrl: 'https://forge-dapi.ifsc-dev.deltatre.digital/v2/content/en-gb/tags/nic-sutton-10015',
        title: 'Nic SUTTON',
        slug: 'nic-sutton-10015',
        neutralSlug: 'nic-sutton-10015',
        externalSourceName: 'athletes',
        externalSourceReference: {
          SourceId: '10015',
          SourceName: 'athletes',
        },
        extraData: {
          country: 'USA',
          federation: {
            id: 20,
            name: 'USA Climbing',
            abbreviation: 'USAC',
          },
          firstName: 'Nic',
          gender: 'male',
          lastName: 'SUTTON',
        },
        fields: {},
      },
      {
        _translationId: '08316e15-7a2a-4a80-b72b-f76b49e3badc',
        _entityId: 'd918d81a-fb96-4472-b860-503071d9d5a2',
        selfUrl: 'https://forge-dapi.ifsc-dev.deltatre.digital/v2/content/en-gb/tags/nicholas-perreth-27',
        title: 'Nicholas PERRETH',
        slug: 'nicholas-perreth-27',
        neutralSlug: 'nicholas-perreth-27',
        externalSourceName: 'athletes',
        externalSourceReference: {
          SourceId: '27',
          SourceName: 'athletes',
        },
        extraData: {
          birthday: '1984-11-29',
          country: 'GER',
          federation: {
            id: 6,
            name: 'Deutscher Alpenverein',
            abbreviation: 'DAV',
          },
          firstName: 'Nicholas',
          gender: 'male',
          lastName: 'PERRETH',
          paraclimbingSportClass: 'Single-leg/ Single-legged Climbing: AL2',
        },
        fields: {},
      },
      {
        _translationId: '002cc4ab-d58b-42e9-8d14-f808abf45a98',
        _entityId: '9f45a070-2d98-407c-b879-1383acdbd590',
        selfUrl: 'https://forge-dapi.ifsc-dev.deltatre.digital/v2/content/en-gb/tags/nicolas-farcy-311',
        title: 'Nicolas FARCY',
        slug: 'nicolas-farcy-311',
        neutralSlug: 'nicolas-farcy-311',
        externalSourceName: 'athletes',
        externalSourceReference: {
          SourceId: '311',
          SourceName: 'athletes',
        },
        extraData: {
          birthday: '1983-07-31',
          country: 'BEL',
          federation: {
            id: 9,
            name: 'Climbing and Mountaineering Belgium',
            abbreviation: 'CMBEL',
            url: 'www.cmbel.be',
          },
          firstName: 'Nicolas',
          gender: 'male',
          lastName: 'FARCY',
        },
        fields: {},
      },
      {
        _translationId: 'c7160a4e-1f93-44ed-81be-22393e64ddf8',
        _entityId: 'ac3eb569-1b12-498d-a824-3c0fb248bba2',
        selfUrl: 'https://forge-dapi.ifsc-dev.deltatre.digital/v2/content/en-gb/tags/martin-schlageter-7',
        title: 'Martin SCHLAGETER',
        slug: 'martin-schlageter-7',
        neutralSlug: 'martin-schlageter-7',
        externalSourceName: 'athletes',
        externalSourceReference: {
          SourceId: '7',
          SourceName: 'athletes',
        },
        extraData: {
          birthday: '1966-03-15',
          country: 'GER',
          federation: {
            id: 6,
            name: 'Deutscher Alpenverein',
            abbreviation: 'DAV',
          },
          firstName: 'Martin',
          gender: 'male',
          lastName: 'SCHLAGETER',
        },
        fields: {},
      },
    ],
    fields: {},
    createdBy: 'Nicholas De Pasquale',
    lastUpdatedBy: 'Claudia Bertolino',
    lastUpdatedDate: '2023-10-19T08:23:18.241Z',
    contentDate: '2023-10-08T11:36:52.47Z',
    context: {
      _translationId: '9b458d8d-ac3d-4398-964e-6db9ab55c82c',
      _entityId: '65726174-49fb-4d37-bff1-9fcb5f9a35cb',
      selfUrl: 'https://forge-dapi.ifsc-dev.deltatre.digital/v2/content/en-gb/tags/ifsc-ywc',
      title: 'IFSC YWC',
      slug: 'ifsc-ywc',
      neutralSlug: 'ifsc-ywc',
      externalSourceReference: {},
      fields: {},
    },
    featured: 0,
    headline: "IFSC CELEBRATES INTERNATIONAL WOMEN'S DAY",
    summary:
      "Sport is one of the most powerful platforms for promoting gender equality and empowering women and girls.\nFor International Women's Day this year, the IOC invited the Olympic Movement to support the UN Women’s campaign by sharing a picture on social media of an inspiring woman in sport. The IFSC",
    thumbnail: {
      title: 'ifsc-climbing-world-cup-wujiang-2023_53230747469_o',
      templateUrl: 'https://res.cloudinary.com/ifsc/image/private/{formatInstructions}/dev/wcqoymq0oe5qspcxcoua',
      thumbnailUrl:
        'https://res.cloudinary.com/ifsc/image/private/t_ratio1_1-size20-f_webp-c_fill/dev/wcqoymq0oe5qspcxcoua',
      format: 'jpg',
      overriddenFormats: {},
      slug: 'ifsc-climbing-world-cup-wujiang-2023-53230747469-o',
      selfUrl:
        'https://forge-dapi.ifsc-dev.deltatre.digital/v2/content/en-gb/photos/ifsc-climbing-world-cup-wujiang-2023-53230747469-o',
    },
  },
  {
    type: ForgeEntityCode.story,
    _translationId: 'd8f5c5ac-f736-42fe-91ab-50d67d237d3f',
    _entityId: '318191b8-3b46-4e9d-af1b-16f38b74c437',
    selfUrl:
      'https://forge-dapi.ifsc-dev.deltatre.digital/v2/content/en-gb/stories/ioc-publishes-new-consensus-statement-on-relative-energy-deficiency-in-sport-to-protect-athlete-health',
    slug: 'ioc-publishes-new-consensus-statement-on-relative-energy-deficiency-in-sport-to-protect-athlete-health',
    title: 'IOC PUBLISHES NEW CONSENSUS STATEMENT ON RELATIVE ENERGY DEFICIENCY IN SPORT TO PROTECT ATHLETE HEALTH',
    tags: [],
    fields: {},
    createdBy: 'Nicholas De Pasquale',
    lastUpdatedBy: 'Nicholas De Pasquale',
    lastUpdatedDate: '2023-10-08T11:35:10.965Z',
    contentDate: '2023-10-08T11:35:10.965Z',
    featured: 0,
    headline: 'IOC PUBLISHES NEW CONSENSUS STATEMENT ON RELATIVE ENERGY DEFICIENCY IN SPORT TO PROTECT ATHLETE HEALTH',
    summary:
      'A new International Olympic Committee (IOC) Consensus Statement, published in the British Journal of Sports Medicine, highlights the risk for athletes of a syndrome affecting health and performance, caused by a mismatch between the calories eaten and burned during exercise – known as Relative Energy Deficiency in Sport (REDs).\nThe',
    thumbnail: {
      title: 'IOC',
      templateUrl: 'https://res.cloudinary.com/ifsc/image/private/{formatInstructions}/dev/cod18evz6d2tg3woy4nr',
      thumbnailUrl:
        'https://res.cloudinary.com/ifsc/image/private/t_ratio1_1-size20-f_webp-c_fill/dev/cod18evz6d2tg3woy4nr',
      format: 'png',
      overriddenFormats: {},
      slug: 'ioc',
      selfUrl: 'https://forge-dapi.ifsc-dev.deltatre.digital/v2/content/en-gb/photos/ioc',
    },
  },
];

export { sampleStories };
